version: "3.8"
services:
  client:
    build: "./wolf-c"
    container_name: wolf
    image: "wolf-c"
    volumes:
      - "${PWD}/wolf-c:/wolf-c"
    restart: on-failure

volumes:
  container:
    name: wolf-c
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/wolf-c"
