services:
  wolf_service:
    image: "wolf_image"
    container_name: wolf_container
    build: "./"
    volumes:
      - "wolf_volume:/wolf-compiler"
    restart: on-failure

volumes:
  wolf_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./"
