version: "3.8"
services:
  client:
    build: "/home/ironman/Desktop/Wolf-Compiler/wolf-c"
    container_name: wolf
    image: "wolf-c"
    volumes:
      - "/home/ironman/Desktop/Wolf-Compiler/wolf-c:/wolf-c"
    restart: on-failure

volumes:
  container:
    name: wolf-c
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/ironman/Desktop/Wolf-Compiler/wolf-c"
