version: "3.8"
services:
  client:
    build: "./wcc"
    container_name: wolf
    volumes:
      - "${PWD}/wcc:/wcc"
    restart: on-failure

volumes:
  container:
    name: wolf-cc
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/wcc"
