services:
  wolf_service:
    container_name: wcc
    image: wcc
    build: .
    mem_limit: 4g
    memswap_limit: 4g
    volumes:
      - ../src:/src
      - ../utils/import:/import
      - ../utils/random:/random
      - ../utils/tests:/tests
      - ./setup.sh:/root/.bashrc
