
services:
  wolf_service:
    container_name: wcc
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: wcc
    volumes:
      - ../src:/src
      - ../utils/import:/import
      - ../utils/project:/project
      - ../utils/random:/random
      - ../utils/tests:/tests
      - ./setup.sh:/root/.bashrc
