services:
  wolf_service:
    container_name: wcc
    build: .
    volumes:
      - ../src:/src
      - ../utils/import:/import
      - ../utils/project:/project
      - ../utils/random:/random
      - ../utils/tests:/tests
      - ./setup.sh:/root/.bashrc
